info:
  contact: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: get all messages
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 测试接口
swagger: "2.0"
